### ISSUE TITLE
Series/Episodes appear as unwatched in Collection after re-creating all groups

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#25] opened 2014-08-19 03:40 UTC
**Reported by aznzhang, Aug 24, 2012**

The option I am referring to is in the Essential tab of JMM Desktop. Upon checking the option and clicking "Recreate All Groups," and then refreshing in Collection, series that I have watched in AniDB show up as unwatched.

**Comment by ElementalCrisis** [comment] 2016-01-21 09:28
I'm unable to reproduce this bug, going to assume it was either something on the users end or fixed in a newer version of JMM.

**Closed by ElementalCrisis** 2016-01-21 09:28 UTC
Labels: Bug - Can't Reproduce
