### ISSUE TITLE
Investigate removing requirement for UAC admin rights on JMM Server

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#20] opened 2014-08-19 02:26 UTC
**Reported by werndlymob, Jul 29, 2012**

Investigate removing requirement for UAC admin rights on JMM Server
http://forum.team-mediaportal.com/threads/my-anime-3.107475/page-19#post-886628

**Jan 14, 2013  Craige1Emmott**

It looks to me its the update program that needs the admin rights. Tho if you can remove the admin requirements from the whole program and just invoke the update process with admin rights, that should be an easy fix(cross fingers). The fix for the server uac should also work on the jmm desktop client, solving yet another issue with jmm needing admin rights when running on a shared PC(not good program ethics).

**Comment by bmfrosty** [comment] 2015-10-29 03:54
Was about to create a new ticked about this.  Would be very good to get JMM to stop creating files in "Program Files".

**Comment by hidden4003** [comment] 2016-06-30 20:57
> 2) It adds the necessary "netsh http add urlacl" commands to the installer so that the Server is able to register the URLs. It registers them for the group Local, so anybody with an account on the computer should be able to bring up the server.

A bit of new info on this, I've tried the following, launched JMM Server with "Run as Administrator" changed port from 8111 to 8113 and back which led to urlacl rules being recreated, I checked the rules with "netsh http show urlacl", rules created accessible to user Everyone.
Then trying to run server as user I just get "Access denied" looking into the log shows that the issue is in ServiceHost. As long as we use ServiceHost which in turn uses http.sys for port sharing, it is impossible to make it run as a user.
I tested on Windows 10 Home.

**Comment by bigretromike** [comment] 2016-07-01 05:11
It just a blind shot but maybe moving to 'Nancy' would help ?

**Comment by hidden4003** [comment] 2016-07-01 06:16
> As long as we use ServiceHost which in turn uses http.sys for port sharing, it is impossible to make it run as a user.
This statement is incorrect and not specific enough it is not the ServiceHost that is preventing it but the http:// urls, if we switch to net.tcp:// this issue should be resolved so it doesn't look like we have to rewrite entire service part as it would be with Nancy.

**Comment by maxpiva** [comment] 2016-07-01 13:43
Better wait till we move JMMServer to a Windows service (In case of
WIndows). Network and system account have the necessary rights.

**Comment by ElementalCrisis** [comment] 2016-07-10 08:16
For the time being this is not possible as JMM Server needs Admin privileges to function correctly. I'm removing this from the 3.6 milestone but keeping it open for further investigation.

**Comment by maxpiva** [comment] 2016-09-23 04:39
Done.

**Closed by maxpiva** 2016-09-23 04:39 UTC
Labels: Enhancement - Core Change
