### ISSUE TITLE
Several individual episodes will not process - MariaDB

### ISSUE THREAD

**Issue by Animeimp** [japanesemediamanager/jmmserver#183] opened 2015-11-02 23:48 UTC
I have 7 episodes that will not process.  They sit in the inbound directory, and do not show up in the Unprocessed file list.  I checked the log file, and they all have an error like this:

[2015-11-02 14:19:10:449] Error|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_ProcessFile.ProcessCommand Error processing CommandRequest_ProcessFile: 19928 - NHibernate.Exceptions.GenericADOException: could not insert: [JMMServer.Entities.AnimeEpisode][SQL: INSERT INTO `AnimeEpisode` (AniDB_EpisodeID, AnimeSeriesID, DateTimeCreated, DateTimeUpdated) VALUES (?, ?, ?, ?)] ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '172507' for key 'UIX_AnimeEpisode_AniDB_EpisodeID'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd) in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\AbstractBatcher.cs:line 216
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder) in d:\CSharp\NH\nhibernate\src\NHibernate\Id\Insert\AbstractSelectingDelegate.cs:line 38
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder) in d:\CSharp\NH\nhibernate\src\NHibernate\Id\Insert\AbstractSelectingDelegate.cs:line 47
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Boolean[] notNull, SqlCommandInfo sql, Object obj, ISessionImplementor session) in d:\CSharp\NH\nhibernate\src\NHibernate\Persister\Entity\AbstractEntityPersister.cs:line 2563
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session) in d:\CSharp\NH\nhibernate\src\NHibernate\Persister\Entity\AbstractEntityPersister.cs:line 2988
   at NHibernate.Action.EntityIdentityInsertAction.Execute() in d:\CSharp\NH\nhibernate\src\NHibernate\Action\EntityIdentityInsertAction.cs:line 75
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable) in d:\CSharp\NH\nhibernate\src\NHibernate\Engine\ActionQueue.cs:line 136
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) in d:\CSharp\NH\nhibernate\src\NHibernate\Event\Default\AbstractSaveEventListener.cs:line 260
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSave(Object entity, Object id, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) in d:\CSharp\NH\nhibernate\src\NHibernate\Event\Default\AbstractSaveEventListener.cs:line 187
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) in d:\CSharp\NH\nhibernate\src\NHibernate\Event\Default\AbstractSaveEventListener.cs:line 119
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event) in d:\CSharp\NH\nhibernate\src\NHibernate\Event\Default\DefaultSaveOrUpdateEventListener.cs:line 163
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event) in d:\CSharp\NH\nhibernate\src\NHibernate\Event\Default\DefaultSaveOrUpdateEventListener.cs:line 148
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.PerformSaveOrUpdate(SaveOrUpdateEvent event) in d:\CSharp\NH\nhibernate\src\NHibernate\Event\Default\DefaultSaveOrUpdateEventListener.cs:line 78
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event) in d:\CSharp\NH\nhibernate\src\NHibernate\Event\Default\DefaultSaveOrUpdateEventListener.cs:line 53
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event) in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\SessionImpl.cs:line 2613
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj) in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\SessionImpl.cs:line 539
   at JMMServer.Repositories.AnimeEpisodeRepository.Save(ISession session, AnimeEpisode obj) in C:\Projects\GitHub\JMMServer\JMMServer\Repositories\AnimeEpisodeRepository.cs:line 29
   at JMMServer.Entities.AniDB_Episode.CreateAnimeEpisode(ISession session, Int32 animeSeriesID) in C:\Projects\GitHub\JMMServer\JMMServer\Entities\AniDB_Episode.cs:line 116
   at JMMServer.Entities.AnimeSeries.CreateAnimeEpisodes(ISession session) in C:\Projects\GitHub\JMMServer\JMMServer\Entities\AnimeSeries.cs:line 327
   at JMMServer.Entities.AnimeSeries.CreateAnimeEpisodes() in C:\Projects\GitHub\JMMServer\JMMServer\Entities\AnimeSeries.cs:line 316
   at JMMServer.Commands.CommandRequest_ProcessFile.ProcessFile_AniDB(VideoLocal vidLocal) in C:\Projects\GitHub\JMMServer\JMMServer\Commands\CommandRequest_ProcessFile.cs:line 262
   at JMMServer.Commands.CommandRequest_ProcessFile.ProcessCommand() in C:\Projects\GitHub\JMMServer\JMMServer\Commands\CommandRequest_ProcessFile.cs:line 69

I have tried moving them out of the directory, deleting missing files, and the moving back into the directory, same error.  I upgraded to the latest release today (3.4.5.3) and same error.

BTW, the Discord link from the JMM page says it has expired.

**Comment by ElementalCrisis** [comment] 2015-11-03 01:09
I believe this is the problem. 
 > Duplicate entry '172507' for key 'UIX_AnimeEpisode_AniDB_EpisodeID'

Remove that entry (animeepisode table) and see if that fixes the problem. 

Also the Discord link is set to never expire, just tested it myself and was able to enter, I'll look into it.

**Comment by Animeimp** [comment] 2015-11-03 01:24
Will check the table, but shouldn't the remove missing files process clear that table entry so that a manual edit isn't needed?

**Comment by ElementalCrisis** [comment] 2015-11-03 01:42
Sadly I don't know, though I'm sure @jmediamanager can answer that question way better than I ever could. :)

**Comment by jmediamanager** [comment] 2015-11-03 01:47
I've just replicated this error on my machine, so will be looking at it today

**Comment by jmediamanager** [comment] 2015-11-03 01:53
@Animeimp can you give me an example of which files you are having issues with?

For me it is an issue with World Trigger eps 50 and 51
It looks like initially AniDB created a new series for these eps, and then subsequently changed it so they are now added to the original series.

**Comment by AreFinstad** [comment] 2015-11-03 03:10
@Animeimp the reason why the discord link might not have worked is because the servers had some issues today (very rare thing TBH) and was fixed in around 20min. it should work fine now for sure.

**Comment by Animeimp** [comment] 2015-11-03 03:44
@jmediamanager it is World Trigger 50-52, and Ame-iro Cocoa S2 - 05 and Brave Beats - 02.

@AreFinstad Yes, it is working now, thank you.

**Comment by jmediamanager** [comment] 2015-11-03 04:30
So what I did to fix it is as follows

1 - Find the series that those episodes are attached to (using file search)
2 - Open the series, and then delete it (this series probably doesn't exist on AniDB anymore, you can test by clicking the AniDB link)
3 - Move the files to a temporary folder
4 - in JMM Server, select "Remove Missing Files"
5 - Wait until this has finished by checking the JMM server log
6 - try and import those files again

**Comment by ElementalCrisis** [comment] 2016-07-24 11:10
Hmm, was this an actual issue with JMM or was it caused by AniDB? I'm unable to replicate it and wondering if it was a just a one time issue.

**Comment by ElementalCrisis** [comment] 2016-08-02 22:48
Going to close this issue as @hidden4003 and myself have been unable to replicate. @Animeimp please feel free to reopen if the issue is still present.

**Closed by ElementalCrisis** 2016-08-02 22:48 UTC
Labels: Bug - Low Priority, In Progress
